[tool.poetry]
name = "root"
version = "0.0.0"
description = ""
authors = ["Kiran Gadhave <kirangadhave2@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
cookiecutter = "^2.1.1"
jupyterlab = "^3.5.2"
jupyter-packaging = "^0.12.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
