version: "3.8"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
      - ~/.nb_proj/pypi:/home/vscode/pypi
      - ~/.nb_proj/ext-mnt:/home/vscode/.vscode-server/extensions
      # And/or for VS Code Insiders
      - ~/.nb_proj/ext-mnt-insiders:/home/vscode/.vscode-server-insiders/extensions
    command: sleep infinity

# volumes:
#   pypi:
#   ext-mnt:
#   ext-mnt-insiders:
