version: "3.8"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/notebook-vis-integration:cached
      - ext-mnt:/home/vscode/.vscode-server/extensions
      # And/or for VS Code Insiders
      - ext-mnt-insiders:/home/vscode/.vscode-server-insiders/extensions
    ports:
      - 8080:8080

volumes:
  ext-mnt:
  ext-mnt-insiders:
