# a mybinder.org-ready environment for demoing interactivede
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate interactivede-demo
#
name: interactivede-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.11,<3.9.0a0
  - jupyterlab >=3.6,<4.0.0a0
  # labextension build dependencies
  - nodejs >=18,<19
  - pip
  - wheel
  # additional packages for demos
  - ipywidgets
  - pandas
  - numpy
  - altair
